// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	grpc.proto

It has these top-level messages:
	BroadcastRequest
	BroadcastResponse
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BroadcastRequest struct {
	Nonce     uint64 `protobuf:"varint,1,opt,name=nonce" json:"nonce,omitempty"`
	Key       []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Signature []byte `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (m *BroadcastRequest) Reset()                    { *m = BroadcastRequest{} }
func (m *BroadcastRequest) String() string            { return proto.CompactTextString(m) }
func (*BroadcastRequest) ProtoMessage()               {}
func (*BroadcastRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BroadcastRequest) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *BroadcastRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *BroadcastRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *BroadcastRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type BroadcastResponse struct {
}

func (m *BroadcastResponse) Reset()                    { *m = BroadcastResponse{} }
func (m *BroadcastResponse) String() string            { return proto.CompactTextString(m) }
func (*BroadcastResponse) ProtoMessage()               {}
func (*BroadcastResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*BroadcastRequest)(nil), "grpc.BroadcastRequest")
	proto.RegisterType((*BroadcastResponse)(nil), "grpc.BroadcastResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for XoxoService service

type XoxoServiceClient interface {
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc1.CallOption) (*BroadcastResponse, error)
}

type xoxoServiceClient struct {
	cc *grpc1.ClientConn
}

func NewXoxoServiceClient(cc *grpc1.ClientConn) XoxoServiceClient {
	return &xoxoServiceClient{cc}
}

func (c *xoxoServiceClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc1.CallOption) (*BroadcastResponse, error) {
	out := new(BroadcastResponse)
	err := grpc1.Invoke(ctx, "/grpc.XoxoService/Broadcast", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for XoxoService service

type XoxoServiceServer interface {
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastResponse, error)
}

func RegisterXoxoServiceServer(s *grpc1.Server, srv XoxoServiceServer) {
	s.RegisterService(&_XoxoService_serviceDesc, srv)
}

func _XoxoService_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XoxoServiceServer).Broadcast(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.XoxoService/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XoxoServiceServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _XoxoService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.XoxoService",
	HandlerType: (*XoxoServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "Broadcast",
			Handler:    _XoxoService_Broadcast_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "grpc.proto",
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2f, 0x2a, 0x48,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xf2, 0xb8, 0x04, 0x9c, 0x8a,
	0xf2, 0x13, 0x53, 0x92, 0x13, 0x8b, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44,
	0xb8, 0x58, 0xf3, 0xf2, 0xf3, 0x92, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x82, 0x20, 0x1c,
	0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x10, 0x13,
	0xa4, 0xae, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x19, 0x2c, 0x06, 0xe1, 0x08, 0xc9, 0x70, 0x71,
	0x16, 0x67, 0xa6, 0xe7, 0x25, 0x96, 0x94, 0x16, 0xa5, 0x4a, 0xb0, 0x80, 0x65, 0x10, 0x02, 0x4a,
	0xc2, 0x5c, 0x82, 0x48, 0xf6, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x1a, 0x79, 0x73, 0x71, 0x47,
	0xe4, 0x57, 0xe4, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xd9, 0x70, 0x71, 0xc2, 0xd5,
	0x08, 0x89, 0xe9, 0x81, 0xdd, 0x8c, 0xee, 0x48, 0x29, 0x71, 0x0c, 0x71, 0x88, 0x61, 0x49, 0x6c,
	0x60, 0xef, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x53, 0x78, 0x77, 0xec, 0x00, 0x00,
	0x00,
}
